### ISSUE TITLE
Any way to change the target Scope  RG

### ISSUE THREAD

**Issue by rdoloto-nps** [mikedzikowski/ZTAImage#24]
Any way to change the target Scope  RG instead of Subcription

**Comment by mikedzikowski** [comment]
Hello, 

We have moved this repo to the following location: https://github.com/Azure/missionlz/tree/main/src/bicep/add-ons/Imaging 

There have been numerous updates and features added. Please use the latest code from the above location and post and issues to the referenced repo. 

Thank you! 

Mike
